// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/pavlovskyive/architecture-lab-3/server/menu"
	"github.com/pavlovskyive/architecture-lab-3/server/orders"
)

// Injectors from modules.go:

func ComposeAPIServer(port HTTPPortNumber) (*RestaurantAPIServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := menu.NewStore(db)
	httpHandlerFunc := menu.HTTPHandler(store)
	ordersStore := orders.NewStore(db)
	ordersHTTPHandlerFunc := orders.HTTPHandler(ordersStore)
	restaurantAPIServer := &RestaurantAPIServer{
		Port:          port,
		MenuHandler:   httpHandlerFunc,
		OrdersHandler: ordersHTTPHandlerFunc,
	}
	return restaurantAPIServer, nil
}
